### ISSUE TITLE
Ligas rotas para Programación en C

### ISSUE THREAD

**Issue by jlrzarcor** [palmoreck/programming-languages#1]
De la Nota 1.2 Sistema de Punto Flotante, al final se tiene lo siguiente:
Referencias:
.
.
.
Lenguaje C de programación. --> esta última es una liga a https://github.com/palmoreck/programming-languages

Intenté explorarla pero en las tareas https://github.com/palmoreck/programming-languages/blob/master/C/ejercicios_de_C/...;
la liga en cada nota para resolver ejercicios está rota.

**Comment by palmoreck** [comment]
@jlrzarcor te refieres a la tarea 1:

https://github.com/palmoreck/programming-languages/blob/master/C/ejercicios_de_C/tarea1.md

?

**Comment by jlrzarcor** [comment]
@palmoreck Prof, más bien me refiero a la liga que esta al final de la nota 1.2
![image](https://user-images.githubusercontent.com/51694352/91924577-b7bca880-ec98-11ea-837c-2979a5b3ed25.png)

**Comment by palmoreck** [comment]
@jlrzarcor le di click a la liga "3. Lenguaje C de programación" de la nota [Sistema_de_punto_flotante.html](https://itam-ds.github.io/analisis-numerico-computo-cientifico/I.computo_cientifico/1.2/Sistema_de_punto_flotante.html) y te lleva a [palmoreck/programming-languages](https://github.com/palmoreck/programming-languages)

Pero mencionas "tareas" en el inicio de este *issue* 

¿Me envías otro screenshot donde estás dando click?

**Comment by jlrzarcor** [comment]
Hola Prof.

https://github.com/palmoreck/programming-languages/blob/master/C/ejercicios_de_C/tarea1.md

![image](https://user-images.githubusercontent.com/51694352/92023422-5fca8400-ed22-11ea-949e-b7b58814d5b6.png)

**Comment by palmoreck** [comment]
Sí, eso es lo que te envié acá https://github.com/palmoreck/programming-languages/issues/1#issuecomment-684076665

> @jlrzarcor te refieres a la tarea 1:
> 
> https://github.com/palmoreck/programming-languages/blob/master/C/ejercicios_de_C/tarea1.md
> 
> ?

**Comment by jlrzarcor** [comment]
@palmoreck cuando doy click en I/1.2, esto es la liga de cada tarea que hace referencia a la nota I/1.2, me lleva a la zona desierta.

**Comment by palmoreck** [comment]
Pero ya está cambiado:

https://github.com/palmoreck/programming-languages/blob/master/C/ejercicios_de_C/tarea1.md
